print("URO Foundations v1.0")
print("Creator: KostantinosV")
print("Email: coveroner1@gmail.com")
print("GitHub: https://github.com/KostantinosV/URO-foundations")
print()
print("Core Idea: Peano's S() operator collapses")
print("creation (0→1) and iteration (1→2).")
print()
print("URO separates them:")
print("- CREATE(): void → existence")
print("- ITERATE(): existence → more existence")
print()
print("URO Principles:")
print("1. Distinction as primitive")
print("2. Observer embedding")
print("3. Paradox tolerance")
print("4. Recursive self-containment")
print()
print("Priority established: December 6, 2025")
